const moduloA = require('./moduloA')
const moduloB = require('./moduloB')

console.log(moduloA.A)
console.log(moduloA.B)
console.log(moduloA.C)
console.log(moduloB.D)
console.log(moduloB.E)
console.log(moduloB.F)
console.log(moduloA,moduloB)